name: nightscout_reporter
description: A web app to generate reports for nightscout data
# version: 1.1.1
# homepage: https://blog.zreptil.de
# author: Andreas.Perlitz <andi@zreptil.de>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0
  intl: ^0.15.8
  crypto: ^2.0.6
  dnd: ^1.4.2
  timezone: ^0.5.4
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.10
  js: ^0.6.1+1

dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.1.1
  sass_builder: ^2.1.3
  intl_translation: ^0.17.4